# Faq
admin_expertise_faq_list:
    path:     /list
    defaults: { _controller: 'PuzzleAdminExpertiseBundle:Faq:list' }

admin_expertise_faq_create:
    path:     /create
    defaults: { _controller: 'PuzzleAdminExpertiseBundle:Faq:create' }

admin_expertise_faq_show:
    path:     /{id}
    defaults: { _controller: 'PuzzleAdminExpertiseBundle:Faq:show' }

admin_expertise_faq_update:
    path:     /{id}/update
    defaults: { _controller: 'PuzzleAdminExpertiseBundle:Faq:update' }
    
admin_expertise_faq_delete:
    path:     /{id}/delete
    defaults: { _controller: 'PuzzleAdminExpertiseBundle:Faq:delete' }